### ISSUE TITLE
Segmentation fault when calling function `is_term_resized`

### ISSUE THREAD

**Issue by cicilzx** [jeaye/ncurses-rs#223]
Hi, I'm developing a fuzzer to test the safe abstraction, and I fonnd a segmentation fault when calling function `is_term_resized`. 

I have tried many inputs, and all of them can trigger the bug. Below is an example input to trigger the segmentation fault. I think it's because missing some pre-condition or post-condition checking when calling the unsafe function `ll::is_term_resized`.

```Rust
use ncurses::is_term_resized;

fn main() {
    let lines = 1;
    let cols = 1;
    let _ = is_term_resized(lines, cols);
}
```

The output is:
```sh
zsh: segmentation fault  cargo run
```

**Comment by correabuscar** [comment]
Many things will break without having a first call to `initscr()`:
> `initscr` is normally the first curses routine to call when initializing a program.
> The initscr code determines the terminal type and initializes all `curses` data structures.

(from `man initscr`)

see example in: https://github.com/jeaye/ncurses-rs/blob/4bd7ab5fea9cf255588100a4d3c842bc7fc6b45a/examples/ex_1.rs#L22

This segfault happens within the ncurses system lib only if you forget to call `initscr` first.

<details>

If you ask me, it shouldn't segfault anyway, but rather, output a nicer message instead, but hey, this is only a thin wrapper for `ncurses`, it isn't say [`cursive`](https://github.com/gyscos/cursive).

</details>

**Comment by cicilzx** [comment]
Thank you for your comment. 

May I ask do you have any thoughts on adding some hints as error handling? (Or maybe a future plan) 
Because Rust developers may not be familiar with C style `ncurses`, and because it is wrapped into a safe Rust API, providing some pre/post condition would be more in line with Rust's specification for unsafe usage.

**Comment by correabuscar** [comment]
> May I ask do you have any thoughts on adding some hints as error handling? (Or maybe a future plan) Because Rust developers may not be familiar with C style `ncurses`, and because it is wrapped into a safe Rust API, providing some pre/post condition would be more in line with Rust's specification for unsafe usage.

I can't answer that, because:
- I'm too newb to know
- I'd have to take some serious time to think about it, preferably not without learning a bunch of things first, about how things are done.

<details>

but without thinking about it, I'd probably build a new lib which would wrap this `ncurses-rs` one and just make sure each call checks if it was inited via something akin to initscr already(presumably there might be other ways other than initscr to init this, if not, I'd just make sure it's not, first), and if not, maybe panic however I'd try to avoid it since it's not supposed to panic if it's a library (or so I "hear").
Then perhaps there's some idiomatic rust way to do such invariants checking without having a call within each function that's being wrapped.

In the context of this similar issue https://github.com/jeaye/ncurses-rs/issues/222 though, I'd probably make sure the precondition (also)checks if that's a file and it's readable by current(effective?) user (maybe even if it's a symlink and it's readable it would work, but for sure I'd "fail" early if it's a dir, else I'd expect the ncurses lib would segfault instead), and only then forward it to `ncurses-rs`.

</details>

**Comment by jeaye** [comment]
Hey! Thanks for the report. From what I gather, due to the helpful responses from @correabuscar, this boils down to a misuse of ncurses. As mentioned, ncurses-rs is a thin wrapper and isn't trying to do any hand holding. Other libs, like cursive, can do a much better job of that. In other words, if it crashes with C, it'll crash with ncurses-rs.

Do we feel ok closing this ticket?
