### ISSUE TITLE
Should  ncurses-rs perform / expose `setlocale`.

### ISSUE THREAD

**Issue by dpc** [jeaye/ncurses-rs#66]
For wide characters to work, before initializing ncurses the following must be done:

```
setlocale(LC_CTYPE, "");
```

Right now I've resorted to using https://github.com/mahkoh/posix.rs.git, but it seems an overkill to include another library to do something that is a part of standard procedure.

How about including setlocale in ncurses-rs?

**Comment by jeaye** [comment]
Since `setlocale` isn't part of ncurses, I'm quite hesitant to put it in. Also, since ncurses-rs right now is just a super minimal wrapper, this seems beyond its scope.

With that said, there is #46 which wants the wrapping to be less minimal and more Rustic. Since I'm not even writing Rust these days, this won't happen until I am, or I pick up a new contributer to the repo (maybe you!). Anyway, I imagine such a wrapper automagically handling setlocale invisibly in this case.

**Comment by dpc** [comment]
I'm currently happy with the way ncurses-rs is, and I understand and agree with your rationale.

**Comment by pmachata** [comment]
It took me a while to figure out the setlocale stuff.  I hope you don't mind that I hijack the bug report to post the resulting snippet.

```
extern "C" {
    pub fn setlocale(category: i32, locale: *const u8) -> *const u8;
}

fn main() {
    unsafe {
        setlocale(0 /* = LC_CTYPE */, "".as_ptr());
    }
    /* ... */
}
```

**Comment by dpc** [comment]
I was told that does not guarantee zero-byte ending. 

Right now I use this to manualy add 0:
https://github.com/dpc/rhex/blob/6bd8171f1b0639a0f9b994cd8bd6a478605c6e66/src/ui/curses.rs#L189

Without it I get subtle bugs that sometimes unicode rendering stops working.

**Comment by pmachata** [comment]
Right you are:
```
        setlocale(0 /* = LC_CTYPE */, "foo".as_ptr());
        setlocale(0 /* = LC_CTYPE */, "bar".as_ptr());
```
```
$ eu-readelf -x .rodata target/hello_world | grep foo
  0x000001a0 666f6f62 61720000 00000000 00000000 foobar..........
```

**Comment by jeaye** [comment]
setlocale was exposed in 0d8b1ec
